### ISSUE TITLE
Question to state of conversion of pegjs to PHP

### ISSUE THREAD

**Issue by Hyper-Node** [MarcelBolten/phpeggy#3]
Hello Marcel, 

Currently, we are working to create a php based parser, 
from a project which was written in javascript and nodejs in wikipedia/mediawiki which currently is generating a javascript based parser with peggy. 
(https://phabricator.wikimedia.org/T312089)   

It's great to have such modules like phpeggy which enable the initial steps of creating a 
parser in php, thanks for all efforts in this development. We have some questions 
about the state of conversion method, as there also is a 'develop' branch which is very active. 

Some  concrete questions: 
- Will it be possible to convert action blocks to php ? 
- Will it be possible to convert javascript initializer code in parser.pegjs to php ?, here we use node modules to define global functions which are called in the action blocks currently   
- If one or both not, what would you suggest to convert the javascript to php ?

**Comment by MarcelBolten** [comment]
Hi Johannes,

Thanks for your interest in PHPeggy.

> - Will it be possible to convert action blocks to php ?

You can and actually have to write the action blocks in php if you use the phpeggy plugin for peggy.

> - Will it be possible to convert javascript initializer code in parser.pegjs to php ?, here we use node modules to define global functions which are called in the action blocks currently

Yes, the initializer code has to be in php as well. You will need to provide php functions that perform the same task as your node modules if that is what you want.

> - If one or both not, what would you suggest to convert the javascript to php ?

I'm not quite sure if I fully understand what you want to achieve. PHPeggy does not do any js to php conversion for you. You will have to write/provide php code instead of js.

For the next major release (current dev branch) I'm thinking about to convert the per-parse initializer to a class method but keep the global initializer outside of the parser class.

Anyways, I am wondering why you don't use wikipeg (https://github.com/wikimedia/wikipeg)?

Maybe you can better assess if phpeggy is what you are looking for by having a look into the [examples](https://github.com/MarcelBolten/phpeggy/blob/master/examples) and [tests](https://github.com/MarcelBolten/phpeggy/blob/master/test/fixtures), e.g., https://github.com/MarcelBolten/phpeggy/blob/master/test/fixtures/chr-unicode.pegjs

Let me know if you have further questions.

Cheers,
Marcel

**Comment by Hyper-Node** [comment]
Hello Marcel, 

thanks for the informative answer. This clarified a lot, probably we have to transcribe javascript to php then. I think wikipeg is a great suggestion, thanks for the hint. 

Best Regards, 
Johannes

**Comment by physikerwelt** [comment]
Hi Marcel, Johannes,

thank you for your fruitful discussion. I may add a clarifying information regarding wikipeg

> Anyways, I am wondering why you don't use wikipeg (https://github.com/wikimedia/wikipeg)?

wikipeg and texvcjs are mutually exclusive. wikipeg does not convert math tags whereas texvcjs deals with math tags only. However, both projects were created originally by a similar set of authors.

**Comment by MarcelBolten** [comment]
> wikipeg and texvcjs are mutually exclusive

I would say the two different tools that cannot be compared this way.

> wikipeg does not convert math tags

Yes, because it is a parser generator like Peggy.
However, if you are about to port all your texvcjs parser.pegjs action blocks to php and write a new parser.pegphp file you should be able to use wikipeg to generate a parser in php. I thought it might be beneficial for you to use an "in-house" solution. But of course I'm happy if you want to use Peggy with the PHPeggy plugin.

**Comment by physikerwelt** [comment]
We decided to go with phpeggy (cf https://phabricator.wikimedia.org/T312528) I think we can close this ticket.

**Comment by physikerwelt** [comment]
@MarcelBolten, this is live https://github.com/wikimedia/mediawiki-extensions-Math/blob/b5d3bca4b47d258fee1773ae52627c79803f1e50/src/TexVC/Parser.php Let us know when there are updates regarding the new release.

**Comment by MarcelBolten** [comment]
@physikerwelt I just published PHPeggy 2.0

**Comment by physikerwelt** [comment]
The update seems to have worked smoothly. I did not really understand how to update the options, but it still works. https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Math/+/904098

**Comment by physikerwelt** [comment]
Unfortunately, we can not update, since we run PHP7 in production.
