### ISSUE TITLE
Regex Translation Bug in phpeggy. 

### ISSUE THREAD

**Issue by Hyper-Node** [MarcelBolten/phpeggy#4]
Phpeggy generates regular expressions which are not suitable for PHP 7.4 in some Unicode cases. 

I created a gist, which shows the problematic regexes:
https://gist.github.com/Hyper-Node/e103c1f3cf407a10dec9b137331ade7f

Expressions which are denoted as 
`	 [\u0080-\ud7ff\]\[\ue000-\uffff\]] `	in the peg-file. 

would have to be translated into 
`	[\x{0080}- .... `	
instead of currently: 
`	[\x80- .... `	

Configuration from package.json: 

`		"peggy": "1.0.0",
		"phpeggy": "^1.0.1"
`

**Comment by MarcelBolten** [comment]
Hi @Hyper-Node,

The gist is not proving your point. The pattern is not working because the escaping is wrong (see code below).
The parser is handling the escaping correctly as far as I can tell (`[\u0080-\u00ff]` in a grammar will be `"/^[\\x80-\\x{00FF}]/"` in the php parser).
I think it would be helpful if you can provide a minimal grammar file and some example input.

run on PHP 7.4.32 (`docker run -it --rm php:7.4.32-cli-alpine php -a`)
~~~PHP
$input = "\u{0080}\u{00C5}\u{00f6}\u{00fc}";
print("input: " . $input . "\n");

$patterns = [
    // working pattern
    // expected output: number ~ true
    "[\x{0080}-\x{0FFF}]+",
    // faulty pattern: \xhh not escaped in double quotes
    // PHP Warning, pattern incorrect
    // output: false
    "[\x80-\x{0FFF}]+",
    // \xhh in double quotes needs extra escaping
    "[\\x80-\x{0FFF}]+",
    // string in single quotes not
    '[\x80-\x{0FFF}]+',
];

foreach ($patterns as $key => $pattern) {
    echo "\n", 'pattern ', $key, ': ', $pattern;

    $res = mb_ereg($pattern, $input, $match);
    echo "\n ", 'mb_ereg return: ', var_export($res), ', match: ', var_export($match);
}
~~~
output:
~~~
input: �Åöü

pattern 0: [\x{0080}-\x{0FFF}]+
 mb_ereg return: 8, match: array (
  0 => '�Åöü',
)
pattern 1: [▒-\x{0FFF}]+
Warning: mb_ereg(): Pattern is not valid under UTF-8 encoding in php shell code on line 21

 mb_ereg return: false, match: array (
)
pattern 2: [\x80-\x{0FFF}]+
 mb_ereg return: 8, match: array (
  0 => '�Åöü',
)
pattern 3: [\x80-\x{0FFF}]+
 mb_ereg return: 8, match: array (
  0 => '�Åöü',
)
~~~

[PHP Sandbox at onlinephp.io](https://onlinephp.io?s=lVNdb9owFH1H4j_cRZWANcHRtA9Gx6qqHdrLJB6mTVqDOie5kIhgZ7bT0lXst-_aCQHR7YE8-Dr349zjY98Pl2VWdjtnuSgrAxPwouopDEfh1tnrN7VdvG1sYu3V6PUra6fT6c3Wu-h2SpUL0_ccxhg8GEKDNyQ84Q0ohVqU3BhUQlOX224H6GMMHqRa5WIJTbD146bExGAKsjIOVVTrGBX8AaMqrNO822hTkw3shuhs5-ee32IseFWYxx30GKJNloGQBlAnvCTsXEAqq7hA-FVJg7qtnH2ewXeuBDHzd_WUnUiliFWbtuO24IU-4DQK_83H9T_uCQIx1XReo3hNjJq2WP8H00ZZ3QhOkz2Akw2_3jGT3r6YEo0GhQW3EhsJmTGlHjO2zE1WxcNErtlDvsrXmOacudX-BsQShc6l0MEXbjIWFzJma65JH6ZVwr7i5ts1m3GlUQ3dw6rPEYTBex78vgp-nL_0J1HUj6LBOIrYxeXwRe8nRBGddO7W9kJpd_OOeO8Dn8KwCUyndWAvyEktrCqnwZNkQrqbsmLxNIVY8WSFJKLGe1S8AENiaTiRzRGVZyRqBnM3PwupkCcZ9PeDxDWcrfARJh9h5xzAU80Bk0y66fOht3vBPd_lk2fs9o3fwduaM4V2OtfxHSpcto38ZpzJrrlJMjvPhy3A9miK6FGZyg4b4d9zdUdzLJXpW-SBb50O4Vm4xd12O38B&v=8.1.11%2C8.0.24%2C7.4.32%2C7.4.29%2C7.4.0)

**Comment by MarcelBolten** [comment]
Hi @Hyper-Node ,

Do you still encounter the problem with your regular expressions or did you have a chance to look further into it?

I would like to close the issue if it turned out to be unrelated to phpeggy.

**Comment by Hyper-Node** [comment]
Hey Marcel, I had a brief look over the issue again locally and the regexes (of TexVC-PHP) are finding such Unicode inputs as
`$input = "\u{0080}\u{00C5}\u{00f6}\u{00fc}";`  without translating the regexes in the php-grammar in the way described in the first comment. I suppose the issue was caused by an earlier version of a test case in TexVC-PHP with erroneous input notation. 

Thanks for the hints. I think this can be closed.
